/**
 * Code Preview Component
 * 
 * Shared component for displaying R code with collapsible panel and copy functionality.
 * Automatically handles metadata display and copying.
 */

import { Component, input, signal, computed, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { extractMetadata, stripMetadata } from '../../../core/r-codegen/metadata-parser';
import { DialogMetadata } from '../../../core/r-codegen/dialog-metadata';
import { ToastService } from '../../../core/services/toast.service';

@Component({
  selector: 'app-code-preview',
  standalone: true,
  imports: [CommonModule, TranslateModule],
  template: `
    <div class="code-preview-section">
      <div class="flex items-center justify-between mb-2">
        <div class="flex items-center gap-2">
          @if (metadata() && showMetadata()) {
            <span class="badge badge-sm badge-info">
              Generated by: {{ getDialogName(metadata()!) }}
            </span>
          }
        </div>
        <div class="flex items-center gap-2">
          <button 
            class="btn btn-ghost btn-xs gap-1"
            (click)="copyCode()"
            title="Copy code"
          >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
            </svg>
            Copy
          </button>
          @if (collapsible()) {
            <button 
              class="btn btn-ghost btn-xs gap-1"
              (click)="isExpanded.set(!isExpanded())"
            >
              {{ isExpanded() ? 'Hide Code' : 'Show Code' }}
            </button>
          }
        </div>
      </div>
      
      @if (!collapsible() || isExpanded()) {
        <pre class="code-block">{{ displayCode() }}</pre>
      }
    </div>
  `,
  styles: [`
    .code-preview-section {
      border-top: 1px solid hsl(var(--b3));
      padding-top: 0.75rem;
    }
    .code-block {
      background: hsl(var(--b2));
      border-radius: 0.5rem;
      padding: 0.75rem;
      font-family: 'Fira Code', 'Monaco', monospace;
      font-size: 0.75rem;
      overflow-x: auto;
      max-height: 200px;
      white-space: pre-wrap;
      word-wrap: break-word;
    }
  `]
})
export class CodePreviewComponent {
  private readonly toastService = inject(ToastService);

  // Inputs
  code = input.required<string>();
  collapsible = input<boolean>(true);
  showMetadata = input<boolean>(true);

  // Internal state
  isExpanded = signal(false);

  // Computed
  metadata = computed(() => {
    const codeValue = this.code();
    return codeValue ? extractMetadata(codeValue) : null;
  });

  displayCode = computed(() => {
    const codeValue = this.code();
    if (!codeValue) return '';
    // Show code without metadata for readability
    return stripMetadata(codeValue);
  });

  copyCode(): void {
    const codeToCopy = this.code();
    if (!codeToCopy) return;

    // Copy full code including metadata
    navigator.clipboard.writeText(codeToCopy).then(() => {
      this.toastService.success('Code copied to clipboard');
    }).catch(err => {
      console.error('Failed to copy code:', err);
      this.toastService.error('Failed to copy code');
    });
  }

  getDialogName(metadata: DialogMetadata): string {
    // Convert dialogId to readable name
    // e.g., "climatic-summary" -> "Climatic Summary"
    return metadata.dialogId
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }
}
