import { Component, OnInit, OnDestroy, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TranslateModule } from '@ngx-translate/core';
import { Subscription } from 'rxjs';
import { RService } from '../../core/services/r.service';
import { ToastService } from '../../core/services/toast.service';
import { LanguageService } from '../../core/services/language.service';
import { OutputEntry } from '../../core/models/r.model';
import { extractMetadata, stripMetadata } from '../../core/r-codegen/metadata-parser';
import { DialogMetadata } from '../../core/r-codegen/dialog-metadata';

@Component({
  selector: 'app-output-panel',
  standalone: true,
  imports: [CommonModule, TranslateModule],
  template: `
    <div class="output-panel-container flex flex-col bg-base-100">
      <!-- Header -->
      <div class="flex-shrink-0 panel-header bg-base-200 border-b border-base-300">
        <div class="flex items-center gap-2">
          <span class="font-medium">{{ 'OUTPUT.TITLE' | translate }}</span>
          <span class="badge badge-sm badge-ghost">{{ entries().length }}</span>
        </div>
        <div class="flex items-center gap-1">
          <button 
            class="btn btn-ghost btn-xs"
            (click)="toggleCodeDisplay()"
            [class.btn-active]="showCode()"
            [title]="'OUTPUT.TOGGLE_CODE' | translate"
          >
            <span class="text-xs font-mono">&lt;/&gt;</span>
          </button>
          <button 
            class="btn btn-ghost btn-xs"
            (click)="clearOutput()"
            [title]="'OUTPUT.CLEAR' | translate"
          >
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
            </svg>
          </button>
        </div>
      </div>

      <!-- Maximized Plot Modal -->
      @if (maximizedPlotUrl()) {
        <dialog class="modal modal-open" (click)="closeMaximizedPlot()">
          <div class="modal-box max-w-[95vw] max-h-[95vh] w-auto p-2 bg-base-100" (click)="$event.stopPropagation()">
            <div class="flex justify-end gap-2 mb-2">
              <button 
                class="btn btn-ghost btn-sm"
                (click)="exportMaximizedPlot()"
                [title]="'OUTPUT.SAVE_PNG' | translate"
              >
                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                </svg>
                {{ 'OUTPUT.SAVE_PNG' | translate }}
              </button>
              <button class="btn btn-ghost btn-sm btn-circle" (click)="closeMaximizedPlot()">✕</button>
            </div>
            <img 
              [src]="maximizedPlotUrl()" 
              alt="Maximized plot"
              class="max-w-full max-h-[85vh] object-contain mx-auto"
            />
          </div>
          <form method="dialog" class="modal-backdrop">
            <button (click)="closeMaximizedPlot()">close</button>
          </form>
        </dialog>
      }

      <!-- Output Content -->
      <div class="flex-1 min-h-0 overflow-y-auto p-4 space-y-4">
        @if (entries().length === 0) {
          <div class="text-center text-base-content/50 py-12">
            <div class="text-4xl mb-2">📋</div>
            <p>{{ 'OUTPUT.EMPTY_MESSAGE' | translate }}</p>
            <p class="text-sm">{{ 'OUTPUT.EMPTY_HINT' | translate }}</p>
          </div>
        } @else {
          @for (entry of entries(); track entry.id) {
            <div class="output-entry pb-4">
              <!-- Timestamp -->
              <div class="text-xs text-base-content/40 mb-2 flex items-center justify-between">
                <span>{{ entry.timestamp | date:'HH:mm:ss' }}</span>
                <span>{{ entry.duration }}ms</span>
              </div>

              <!-- R Code -->
              @if (showCode()) {
                <div class="output-code mb-2">
                  <div class="flex items-center justify-between mb-1">
                    <div class="flex items-center gap-2">
                      @if (getMetadata(entry.code)) {
                        <span class="badge badge-sm badge-info">
                          Generated by: {{ getDialogName(getMetadata(entry.code)!) }}
                        </span>
                      }
                    </div>
                    <div class="flex items-center gap-1">
                      <button 
                        class="btn btn-ghost btn-xs gap-1"
                        (click)="copyCode(entry.code)"
                        title="Copy code"
                      >
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
                        </svg>
                        Copy
                      </button>
                    </div>
                  </div>
                  <pre class="text-xs whitespace-pre-wrap font-mono bg-base-200 rounded-lg p-2">{{ getDisplayCode(entry.code) }}</pre>
                </div>
              }

              <!-- Result -->
              @if (entry.result.success) {
                @switch (entry.result.result?.type) {
                  @case ('text') {
                    <div class="relative">
                      <pre class="output-result whitespace-pre-wrap font-mono text-sm bg-base-200 p-3 rounded-lg overflow-x-auto">{{ formatTextOutput(entry.result.result?.value) }}</pre>
                      <button 
                        class="btn btn-ghost btn-xs absolute top-1 right-1 opacity-60 hover:opacity-100"
                        (click)="exportText(entry)"
                        [title]="'OUTPUT.SAVE_TXT' | translate"
                      >
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                        </svg>
                      </button>
                    </div>
                  }
                  @case ('plot') {
                    <div class="output-plot relative inline-block">
                      <img 
                        [src]="entry.result.result?.dataUrl || entry.result.result?.path" 
                        [alt]="'OUTPUT.PLOT_ALT' | translate"
                        class="max-w-full rounded-lg shadow-lg cursor-pointer"
                        loading="lazy"
                        (click)="maximizePlot(entry)"
                      />
                      <div class="absolute top-2 right-2 flex gap-1">
                        <button 
                          class="btn btn-ghost btn-xs bg-base-100/80 opacity-70 hover:opacity-100"
                          (click)="maximizePlot(entry)"
                          [title]="'OUTPUT.MAXIMIZE' | translate"
                        >
                          <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4" />
                          </svg>
                        </button>
                        <button 
                          class="btn btn-ghost btn-xs bg-base-100/80 opacity-70 hover:opacity-100"
                          (click)="exportPlot(entry)"
                          [title]="'OUTPUT.SAVE_PNG' | translate"
                        >
                          <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                          </svg>
                        </button>
                      </div>
                    </div>
                  }
                  @case ('dataframe') {
                    <div class="overflow-x-auto">
                      <div class="flex items-center justify-between text-xs text-base-content/60 mb-1">
                        <span>{{ 'OUTPUT.SHOWING_ROWS' | translate: {shown: entry.result.result?.data?.length || 0, total: entry.result.result?.totalRows || 0} }}</span>
                        <button 
                          class="btn btn-ghost btn-xs opacity-60 hover:opacity-100"
                          (click)="exportDataframe(entry)"
                          [title]="'OUTPUT.SAVE_CSV' | translate"
                        >
                          <svg xmlns="http://www.w3.org/2000/svg" class="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                          </svg>
                        </button>
                      </div>
                      <table class="table table-xs table-zebra">
                        <thead>
                          <tr>
                            @for (col of entry.result.result?.columns || []; track col) {
                              <th>{{ col }}</th>
                            }
                          </tr>
                        </thead>
                        <tbody>
                          @for (row of entry.result.result?.data || []; track $index) {
                            <tr>
                              @for (col of entry.result.result?.columns || []; track col) {
                                <td>{{ formatCellValue(row, col) }}</td>
                              }
                            </tr>
                          }
                        </tbody>
                      </table>
                    </div>
                  }
                  @default {
                    <div class="text-base-content/70 text-sm">
                      {{ 'OUTPUT.SUCCESS_DEFAULT' | translate }}
                    </div>
                  }
                }
              } @else {
                <div class="output-error">
                  <div class="font-medium mb-1">{{ 'OUTPUT.ERROR' | translate }}</div>
                  <div>{{ entry.result.error }}</div>
                </div>
              }
            </div>
          }
        }
      </div>
    </div>
  `,
  styles: [`
    :host {
      display: flex;
      flex-direction: column;
      height: 100%;
      overflow: hidden;
    }
    .output-panel-container {
      height: 100%;
      overflow: hidden;
    }
  `]
})
export class OutputPanelComponent implements OnInit, OnDestroy {
  private readonly rService = inject(RService);
  private readonly toastService = inject(ToastService);
  private readonly languageService = inject(LanguageService);
  private subscription?: Subscription;

  entries = signal<OutputEntry[]>([]);
  showCode = signal(true);
  maximizedPlotUrl = signal<string | null>(null);
  private maximizedEntry: OutputEntry | null = null;

  ngOnInit(): void {
    this.subscription = this.rService.output$.subscribe(entries => {
      this.entries.set(entries);
    });
  }

  ngOnDestroy(): void {
    this.subscription?.unsubscribe();
  }

  toggleCodeDisplay(): void {
    this.showCode.update(v => !v);
  }

  clearOutput(): void {
    this.rService.clearHistory();
  }

  maximizePlot(entry: OutputEntry): void {
    const url = entry.result.result?.dataUrl || entry.result.result?.path;
    if (url) {
      this.maximizedPlotUrl.set(url);
      this.maximizedEntry = entry;
    }
  }

  closeMaximizedPlot(): void {
    this.maximizedPlotUrl.set(null);
    this.maximizedEntry = null;
  }

  async exportMaximizedPlot(): Promise<void> {
    if (this.maximizedEntry) {
      await this.exportPlot(this.maximizedEntry);
    }
  }

  formatTextOutput(value: unknown): string {
    if (Array.isArray(value)) {
      return value.join('\n');
    }
    return String(value || '');
  }

  getMetadata(code: string): DialogMetadata | null {
    return extractMetadata(code);
  }

  getDisplayCode(code: string): string {
    return stripMetadata(code);
  }

  getDialogName(metadata: DialogMetadata): string {
    // Convert dialogId to readable name
    // e.g., "climatic-summary" -> "Climatic Summary"
    return metadata.dialogId
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  copyCode(code: string): void {
    if (!code) return;

    navigator.clipboard.writeText(code).then(() => {
      this.toastService.success('Code copied to clipboard');
    }).catch(err => {
      console.error('Failed to copy code:', err);
      this.toastService.error('Failed to copy code');
    });
  }

  formatCellValue(row: Record<string, unknown>, col: string): string {
    const value = row[col];
    if (value === null || value === undefined) {
      return 'NA';
    }
    if (typeof value === 'number') {
      return Number.isInteger(value) ? value.toString() : value.toFixed(4);
    }
    return String(value);
  }

  async exportText(entry: OutputEntry): Promise<void> {
    if (!window.electronAPI?.dialog?.saveFile || !window.electronAPI?.file?.writeText) {
      this.toastService.warning(this.languageService.instant('OUTPUT.EXPORT_NA'));
      return;
    }

    const timestamp = new Date(entry.timestamp).toISOString().slice(0, 19).replace(/:/g, '-');
    const defaultName = `output_${timestamp}.txt`;

    try {
      const result = await window.electronAPI.dialog.saveFile({
        title: this.languageService.instant('OUTPUT.SAVE_TXT'),
        defaultPath: defaultName,
        filters: [{ name: 'Text Files', extensions: ['txt'] }],
      });

      if (!result.canceled && result.filePath) {
        const content = this.formatTextOutput(entry.result.result?.value);
        const writeResult = await window.electronAPI.file.writeText(result.filePath, content);
        
        if (writeResult.success) {
          this.toastService.success(this.languageService.instant('OUTPUT.EXPORT_SUCCESS'));
        } else {
          this.toastService.error(writeResult.error || this.languageService.instant('OUTPUT.EXPORT_FAILED'));
        }
      }
    } catch (error) {
      console.error('Failed to export text:', error);
      this.toastService.error(this.languageService.instant('OUTPUT.EXPORT_FAILED'));
    }
  }

  async exportPlot(entry: OutputEntry): Promise<void> {
    if (!window.electronAPI?.dialog?.saveFile || !window.electronAPI?.file?.writeBase64) {
      this.toastService.warning(this.languageService.instant('OUTPUT.EXPORT_NA'));
      return;
    }

    const dataUrl = entry.result.result?.dataUrl;
    if (!dataUrl) {
      this.toastService.warning(this.languageService.instant('OUTPUT.NO_PLOT_DATA'));
      return;
    }

    const timestamp = new Date(entry.timestamp).toISOString().slice(0, 19).replace(/:/g, '-');
    const defaultName = `plot_${timestamp}.png`;

    try {
      const result = await window.electronAPI.dialog.saveFile({
        title: this.languageService.instant('OUTPUT.SAVE_PNG'),
        defaultPath: defaultName,
        filters: [{ name: 'PNG Images', extensions: ['png'] }],
      });

      if (!result.canceled && result.filePath) {
        const writeResult = await window.electronAPI.file.writeBase64(result.filePath, dataUrl);
        
        if (writeResult.success) {
          this.toastService.success(this.languageService.instant('OUTPUT.EXPORT_SUCCESS'));
        } else {
          this.toastService.error(writeResult.error || this.languageService.instant('OUTPUT.EXPORT_FAILED'));
        }
      }
    } catch (error) {
      console.error('Failed to export plot:', error);
      this.toastService.error(this.languageService.instant('OUTPUT.EXPORT_FAILED'));
    }
  }

  async exportDataframe(entry: OutputEntry): Promise<void> {
    if (!window.electronAPI?.dialog?.saveFile || !window.electronAPI?.file?.writeText) {
      this.toastService.warning(this.languageService.instant('OUTPUT.EXPORT_NA'));
      return;
    }

    const data = entry.result.result?.data;
    const columns = entry.result.result?.columns;
    if (!data || !columns) {
      this.toastService.warning(this.languageService.instant('OUTPUT.NO_TABLE_DATA'));
      return;
    }

    const timestamp = new Date(entry.timestamp).toISOString().slice(0, 19).replace(/:/g, '-');
    const defaultName = `data_${timestamp}.csv`;

    try {
      const result = await window.electronAPI.dialog.saveFile({
        title: this.languageService.instant('OUTPUT.SAVE_CSV'),
        defaultPath: defaultName,
        filters: [{ name: 'CSV Files', extensions: ['csv'] }],
      });

      if (!result.canceled && result.filePath) {
        // Build CSV content
        const csvContent = this.buildCsv(columns, data);
        const writeResult = await window.electronAPI.file.writeText(result.filePath, csvContent);
        
        if (writeResult.success) {
          this.toastService.success(this.languageService.instant('OUTPUT.EXPORT_SUCCESS'));
        } else {
          this.toastService.error(writeResult.error || this.languageService.instant('OUTPUT.EXPORT_FAILED'));
        }
      }
    } catch (error) {
      console.error('Failed to export dataframe:', error);
      this.toastService.error(this.languageService.instant('OUTPUT.EXPORT_FAILED'));
    }
  }

  private buildCsv(columns: string[], data: Record<string, unknown>[]): string {
    const escapeCsvValue = (val: unknown): string => {
      if (val === null || val === undefined) return '';
      const str = String(val);
      if (str.includes(',') || str.includes('"') || str.includes('\n')) {
        return `"${str.replace(/"/g, '""')}"`;
      }
      return str;
    };

    const header = columns.map(escapeCsvValue).join(',');
    const rows = data.map(row => 
      columns.map(col => escapeCsvValue(row[col])).join(',')
    );
    
    return [header, ...rows].join('\n');
  }
}
